import { TJavaOne, TJavaTwo, TJavaThree } from './types'

export const SFJava: {
  JavaOne: TJavaOne
  JavaTwo: TJavaTwo
  JavaThree: TJavaThree
} = {
  JavaOne: {
    1: `public class Ice { static void main(String[] args) { new Random() }`,
    2: `String str = "Java" int x = 10 double y = 3.14 boolean flag = true`,
    3: `if (flag) { x += 5 } else { x = x - 3 }`,
    4: `for (int i = 0 i < 10 i++) { y += i * Math.random() }`,
    5: `if (x > 5) { y = Math.sqrt(x) } else { x = -x }`,
    6: `System.out.println("Random result: " + x + " and y value: " + y)`,
    7: `int z = (int) Math.floor(y) System.out.println("Floor of y is: " + z)`,
    8: `String result = "Code" result += z`,
    9: `if (z % 2 == 0) { result = "Even" } else { result = "Odd" }`,
    10: `double temp = Math.random() * 100`,
    11: `int counter = 0 while (counter < 5) { counter++ }`,
    12: `boolean check = temp > 50 if (check) { temp = temp / 2 } else { temp *= 2 }`,
    13: `System.out.println("Final value: " + temp)`,
    14: `double sum = x + y + z System.out.println("Sum of x, y, and z: " + sum)`,
    15: `System.out.println("Final sum result is: " + sum)`,
    16: `for (int i = 0 i < 3 i++) { sum += i }`,
    17: `if (sum > 10) { sum = Math.pow(sum, 2) } else { sum = Math.log(sum) }`,
    18: `System.out.println("Adjusted sum: " + sum)`,
    19: `String concat = "Result: " + result + " " + sum`,
    20: `System.out.println(concat + " - All values processed!")`,
    21: `int randomValue = (int) (Math.random() * 100)`,
    22: `if (randomValue > 50) { System.out.println("Big value: " + randomValue) }`,
    23: `else { System.out.println("Small value: " + randomValue) }`,
    24: `System.out.println("Random value: " + randomValue)`,
    25: `System.out.println("Code execution finished!")`,
  },
  JavaTwo: {
    1: `public class River { static void main(String[] args) { int a = 0 }`,
    2: `double b = 2.5 String text = "Hello World"`,
    3: `boolean isTrue = (a == 0) if (isTrue) { b = b * 2 }`,
    4: `for (int i = 0 i < 5 i++) { a += i b -= 0.5 }`,
    5: `if (b < 3.0) { text = "Value is small" } else { text = "Value is large" }`,
    6: `System.out.println("Result: " + text)`,
    7: `int sum = a + 10 int product = sum * 2 double division = sum / 2.0`,
    8: `String result = "Sum is: " + sum`,
    9: `if (sum > 15) { result += " - Big" } else { result += " - Small" }`,
    10: `double randomValue = Math.random() * 100`,
    11: `for (int i = 0 i < 3 i++) { randomValue += i }`,
    12: `if (randomValue > 50) { randomValue = Math.pow(randomValue, 2) }`,
    13: `else { randomValue = Math.sqrt(randomValue) }`,
    14: `System.out.println("Random value: " + randomValue)`,
    15: `String finalResult = result + " " + randomValue`,
    16: `System.out.println(finalResult)`,
    17: `int counter = 0 while (counter < 4) { counter++ }`,
    18: `if (counter == 4) { System.out.println("Counter reached 4!") }`,
    19: `else { System.out.println("Counter is still less than 4.") }`,
    20: `double square = Math.pow(counter, 2)`,
    21: `System.out.println("Counter square: " + square)`,
    22: `int diff = a - sum int productDiff = diff * 2 double ratio = (diff != 0)`,
    23: `System.out.println("Difference: " + diff)`,
    24: `randomValue = Math.random() * 100`,
    25: `System.out.println("New random value: " + randomValue)`,
  },
  JavaThree: {
    1: `public class Shirt { public static void main(String[] args) }`,
    2: `String result = "" double value = 0.0 boolean isEven = false`,
    3: `if (a + b > c) { value = a * 2.5 result = "Sum is greater" }`,
    4: `for (int i = 1 i <= 5 i++) { value += i result += " " + i }`,
    5: `isEven = (value % 2 == 0) if (isEven) { result += "The value" }`,
    6: `if (isEven) { result += " - Even value" } else { result += " - Odd value" }`,
    7: `System.out.println("Calculated value is: " + value + ". This is the result.")`,
    8: `int diff = a - b double quotient = (b != 0) ? (double) a / b : 0`,
    9: `String diffResult = "Difference: " + diff + ", Quotient: " + quotient`,
    10: `if (quotient > 1) { diffResult += " - High quotient" }`,
    11: `System.out.println("Here is the final result of the calculations: "diffResult")`,
    12: `while (a < 10) { a++ b += 2 if (a % 2 == 0) { c *= 3 } else { c -= 1 } }`,
    13: `for (int i = 0 i < a i++) { c += i if (i % 3 == 0) { value += i * 1.5 }`,
    14: `System.out.println("Final values: a=" + a + ", b=" + b + ", c=" + c)`,
    15: `value = Math.pow(value, 2) value += Math.sqrt(c) + (a * b)`,
    16: `System.out.println("Squared value: " + value)`,
    17: `boolean flag = (value > 100) if (flag) { "result" }`,
    18: `String status = (flag) ? "Big" : "Small"`,
    19: `System.out.println("The status based on the calculated value.")`,
    20: `System.out.println("Status: " + status)`,
    21: `int sum = a + b + c + (int)value sum += (int) Math.random() * 50`,
    22: `System.out.println("The total sum of all variables.")`,
    23: `value = Math.random() * 50 value += Math.random() * 10`,
    24: `System.out.println("A random value has been calculated: " + value")`,
    25: `System.out.println("End of the program.")`,
  },
}
